---
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - realpath
language: bash
before_install:
- export DISPLAY=:99.0
- Xvfb :99 -ac -screen 0 1024x768x8 &>/dev/null &
install:
- bash <(curl -L https://github.com/vinsonchuong/bash-common-bundle-dependencies/raw/master/bin/bundle-dependencies)
- export PATH=$PWD/bin:$PWD/packages/bin:$PATH
script: bats spec
