---
sudo: required
dist: trusty
language: bash
before_install:
- export DISPLAY=:99.0
- Xvfb :99 -ac -screen 0 1024x768x8 &>/dev/null &
install:
- git clone https://github.com/sstephenson/bats.git
- export PATH=$PWD/bin:$PWD/bats/bin:$PATH
script: bats spec
